package oss3.loan.example.gui;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import oss3.loan.example.Loan;
import oss3.loan.example.LoanTableModel;
import oss3.loan.example.service.JPAManager;

/**
 *
 * @author Thodoris
 */
public class LoanCalculator extends javax.swing.JFrame {

    
    private Loan myLoan;
    /**
     * Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loanAmountTxt = new javax.swing.JTextField();
        interestRateTxt = new javax.swing.JTextField();
        calculateLoanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        installmentsTable = new javax.swing.JTable();
        installmentsNumberCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculator");
        setAlwaysOnTop(true);

        jLabel1.setText("Loan Amount");

        jLabel2.setText("Interest Rate");

        loanAmountTxt.setText("600000");
        loanAmountTxt.setName("loanAmountTxt"); // NOI18N
        loanAmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountTxtActionPerformed(evt);
            }
        });

        interestRateTxt.setText("0.035");
        interestRateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRateTxtActionPerformed(evt);
            }
        });

        calculateLoanBtn.setText("Calculate Loan Installments");
        calculateLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateLoanBtnActionPerformed(evt);
            }
        });

        installmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "AA", "Υπόλοιπο Κεφαλαίου", "Μηνιαία Δόση", "Κεφάλαιο", "Τόκος"
            }
        ));
        jScrollPane1.setViewportView(installmentsTable);

        installmentsNumberCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "12", "24", "36" }));
        installmentsNumberCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installmentsNumberComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Installments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(loanAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(interestRateTxt)
                                    .addComponent(installmentsNumberCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(calculateLoanBtn)
                        .addGap(152, 152, 152))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loanAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(interestRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calculateLoanBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(installmentsNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interestRateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestRateTxtActionPerformed

    private void loanAmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmountTxtActionPerformed

    private void installmentsNumberComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installmentsNumberComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installmentsNumberComboActionPerformed

    private void calculateLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateLoanBtnActionPerformed
        
        Double interestRate = getDoubleValueFromTextField(interestRateTxt);
        Double loanAmount = getDoubleValueFromTextField(loanAmountTxt);
        String si = (String)installmentsNumberCombo.getSelectedItem();
        Integer installmentsNumber = new Integer(si);
        
        if(interestRate.isNaN()){
            JOptionPane.showMessageDialog(null,"Interest rate is not a valid number", "Number Format problem", JOptionPane.ERROR_MESSAGE);
        }
        if(loanAmount.isNaN()){
            JOptionPane.showMessageDialog(null,"Loan Amount is not a valid number", "Number Format problem", JOptionPane.ERROR_MESSAGE);
        }
        else{
            myLoan = new Loan(loanAmount, interestRate, installmentsNumber);
            TableModel loanTableModel = getLoanTableModel();
            installmentsTable.setModel(loanTableModel);
            
            JPAManager.saveLoan(myLoan);
            
        }
    }//GEN-LAST:event_calculateLoanBtnActionPerformed

    private TableModel getLoanTableModel(){
        String[] columnNames = {"AA", "Υπόλοιπο Κεφαλαίου", "Μηνιαία Δόση", "Κεφάλαιο", "Τόκος"};
        TableModel loanTableModel = new LoanTableModel(myLoan,columnNames );
        return loanTableModel;
    }
    
    private double getDoubleValueFromTextField(JTextField interestRateTxt){
        String rateText = interestRateTxt.getText();
        Double rateDouble = Double.NaN;
        try{
            rateDouble = Double.parseDouble(rateText);
        }
        catch(NumberFormatException nfe){
            System.err.println("Wrong interest Rate");
        }
        return rateDouble;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateLoanBtn;
    private javax.swing.JComboBox installmentsNumberCombo;
    private javax.swing.JTable installmentsTable;
    private javax.swing.JTextField interestRateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanAmountTxt;
    // End of variables declaration//GEN-END:variables

}
